spring.application.name=orgo_project

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://PHUVO\\SQLEXPRESS;databaseName=orgo;encrypt=false;trustServerCertificate=true
spring.datasource.username=orgo_user
spring.datasource.password=Orgo@123456

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyentritruong2005@gmail.com
spring.mail.password=bgep nwne esvp ejxl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true